/* ADD MCID COLUMN TO USERS TABLE */
ALTER TABLE users ADD COLUMN mcid  INTEGER NOT NULL REFERENCES marketcenter(id);

/* ADD MCID COLUMN TO CLASSES TABLE */
ALTER TABLE classes ADD COLUMN mcid INTEGER NOT NULL REFERENCES marketcenter(id);

/* ADD COLUMNS TO COMPLETED TABLE */
    
ALTER TABLE completed ADD COLUMN userid INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE completed ADD COLUMN classid INTEGER NOT NULL REFERENCES classes(id) ON DELETE CASCADE;

ALTER TABLE completed ADD COLUMN mcid INTEGER NOT NULL REFERENCES marketcenter(id) ON DELETE CASCADE;;
